# NumPy Tutorial

My personal notes and practice while learning NumPy — the core library for numerical computing and array operations in Python.

In [1]:
# import numpy, conventionally aliased as np
import numpy as np

## 1. Creating NumPy Arrays

Different ways to construct arrays: from a list, ranges, evenly spaced values, filled arrays, identity matrices, and random arrays.

In [2]:
numpy_array = np.array([1,2,3,4,5]) # all elements need to have same type in numpy array

In [3]:
# broadcasting: adds 10 to every element of the array
numpy_array+10

array([11, 12, 13, 14, 15])

In [4]:
arr2 = np.arange(0,10,2) # start, stop, step [start, stop)
print(arr2)

[0 2 4 6 8]


In [5]:
arr3 = np.linspace(0, 200, 5) # start, stop, number of elements
print(arr3)

[  0.  50. 100. 150. 200.]


In [6]:
arr4 = np.zeros(5) # 1 dimensional array of zeroes
print(arr4)

[0. 0. 0. 0. 0.]


In [7]:
arr5 = np.ones(5) # 1 dimensional array of ones
print(arr5)

[1. 1. 1. 1. 1.]


In [8]:
arr6 = np.full(5, 7) # five elements of 7
print(arr6)

[7 7 7 7 7]


In [9]:
# identity matrix: n x n with 1s on the diagonal, 0s elsewhere
identity = np.eye(3)
print(identity)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [10]:
random_arr = np.random.rand(5) # uniform distribution [0, 1)
print(random_arr)

[0.09217326 0.14072239 0.62847506 0.70753364 0.78685674]


In [11]:
random_int = np.random.randint(1, 10, size = 5) # [low, high), size
print(random_int)

[5 5 3 8 9]


## 2. Data Types (dtype)

Checking and converting the data type of array elements.

In [12]:
# check the data type of the array's elements
arr_int = np.array([1,2,3])
print(arr_int.dtype)


int64


In [13]:
# convert array to a different dtype with astype
arr_new_type = arr_int.astype(np.float64)
print(arr_new_type.dtype)

float64


## 3. Multi-dimensional Arrays

Creating and inspecting 2D and 3D arrays, including shape, ndim, and transpose.

In [14]:
# multidimensional arrays
matrix_2d = np.array([[1,2,3], [4,5,6], [7,8,9]])
print(matrix_2d)
print(matrix_2d.shape) # rows and columns
print(matrix_2d.ndim) # number of dimensions
print(matrix_2d.dtype)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)
2
int64


In [15]:
# 3D array: shape is (blocks, rows, columns)
matrix_3d = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(matrix_3d)
print(matrix_3d.shape)
print(matrix_3d.ndim)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
(2, 2, 3)
3


In [16]:
# 2D array of zeros with 3 rows and 4 columns
zeros_2d = np.zeros((3,4))
print(zeros_2d)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [17]:
# another 2D array of zeros (3x3)
zeros_3d = np.zeros((3,3))
print(zeros_3d)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [18]:
# transpose a 3D array with .T
matrix_3d = np.array([[[1,2,3],[4,5,6]]])
print(matrix_3d)

print(matrix_3d.ndim)
print(matrix_3d.shape)

tarr = matrix_3d.T
print(tarr)

[[[1 2 3]
  [4 5 6]]]
3
(1, 2, 3)
[[[1]
  [4]]

 [[2]
  [5]]

 [[3]
  [6]]]


In [19]:
# compare shapes before and after transpose
print(matrix_3d.shape)
print(tarr.shape)

(1, 2, 3)
(3, 2, 1)


## 4. Indexing and Slicing

Accessing elements in 1D and 2D arrays, plus boolean (conditional) indexing.

In [20]:
# Indexing and Slicing:
# 1D

arr = np.array([3,41,5,68,8,9,5])
print("original array", arr)
print(f"First element {arr[0]}")
print(f"Last element {arr[-1]}")
print(f"elements 1 to 3: {arr[1:4]}")
print(f"every other element: {arr[::2]}")

original array [ 3 41  5 68  8  9  5]
First element 3
Last element 5
elements 1 to 3: [41  5 68]
every other element: [3 5 8 5]


In [21]:
#2D
arr_2d = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(f"original array: \n{arr_2d}")
print(f"element at row 1 and column 2: {arr_2d[1,2]}")
print(f"first row: {arr_2d[0,:]}")
print(f"second column: {arr_2d[:,2]}")
print(f"submatrix: first 2 rows and first 2 columns: {arr_2d[ 0:2, 0:2]}")


original array: 
[[1 2 3]
 [4 5 6]
 [7 8 9]]
element at row 1 and column 2: 6
first row: [1 2 3]
second column: [3 6 9]
submatrix: first 2 rows and first 2 columns: [[1 2]
 [4 5]]


In [22]:
# boolean indexing
nums = np.array([1,4,2,5,6,7,3,2,6,7,9,7,5,55,33,43,55,67,87,87])
print(f"elements greater than 10: {nums[nums > 10]}")
print(f"elements that are even: {nums[nums%2==0]}")

elements greater than 10: [55 33 43 55 67 87 87]
elements that are even: [4 2 6 2 6]


## 5. Array Operations (Math & Comparisons)

Element-wise arithmetic, scalar broadcasting, and comparison operators.

In [23]:
# numpy operations
a1 = np.array([1,2,3,4])
a2 = np.array([5,6,7,8])

print(f"Array a1: {a1}")
print(f"Array a2: {a2}")

print("\n--- Element-wise Operations ---")
print(f"Addition: {a1+a2}")
print(f"Subtraction: {a1-a2}")
print(f"Multiplication: {a1*a2}") # bit-wise, not matrix multiplication
print(f"Division: {a1/a2}")
print(f"Power: {a1**a2}")
print(f"Square root: {np.sqrt(a1)} and {np.sqrt(a2)}")

# scalar operations:
print(f"adding 10: {a1+10} and {a2+10}")

# comparison operators:

print(f"comparing greater than 2: {a1>2} and {a2>2}")



Array a1: [1 2 3 4]
Array a2: [5 6 7 8]

--- Element-wise Operations ---
Addition: [ 6  8 10 12]
Subtraction: [-4 -4 -4 -4]
Multiplication: [ 5 12 21 32]
Division: [0.2        0.33333333 0.42857143 0.5       ]
Power: [    1    64  2187 65536]
Square root: [1.         1.41421356 1.73205081 2.        ] and [2.23606798 2.44948974 2.64575131 2.82842712]
adding 10: [11 12 13 14] and [15 16 17 18]
comparing greater than 2: [False False  True  True] and [ True  True  True  True]


## 6. Reshaping and Resizing

Changing array shape with reshape/flatten, transposing, and combining arrays with vstack/hstack/concatenate.

In [24]:
# reshaping and resizing:

arr = np.arange(12)
print(f"Original array: {arr}")

reshaped = arr.reshape(3,4) # must match total size (3*4 =12)
print(f"reshaped array: \n{reshaped}")

# flatten convert to 1D
flattened = reshaped.flatten()
print(f"flattened aray: {flattened}")

# reshape with -1 (auto-calculate dimension)

auto_reshape = arr.reshape(2, -1) # -1 means calculate automatically, 2 here are number of rows and for columns it will be automatically calculated. Can also be more like (2,2,-1)
print(f"auto reshaped: \n {auto_reshape}")

# transpose:
print(f"Transposed matrix: \n {auto_reshape.T}")

# concatenate:
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])

print(f"Matrix a: \n{a} \nand matrix b: \n {b}")

print(f"vertical stack: \n {np.vstack((a,b))}")
print(f"horizontal stack: \n {np.hstack((a,b))}")
print(f"another way of vstack: \n{np.concatenate((a,b), axis = 0)}") # vertical stack when axis = 0
print(f"another way of hstack: \n{np.concatenate((a,b), axis = 1)}") # horizontal stack when axis = 1



Original array: [ 0  1  2  3  4  5  6  7  8  9 10 11]
reshaped array: 
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
flattened aray: [ 0  1  2  3  4  5  6  7  8  9 10 11]
auto reshaped: 
 [[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]
Transposed matrix: 
 [[ 0  6]
 [ 1  7]
 [ 2  8]
 [ 3  9]
 [ 4 10]
 [ 5 11]]
Matrix a: 
[[1 2]
 [3 4]] 
and matrix b: 
 [[5 6]
 [7 8]]
vertical stack: 
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]
horizontal stack: 
 [[1 2 5 6]
 [3 4 7 8]]
another way of vstack: 
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
another way of hstack: 
[[1 2 5 6]
 [3 4 7 8]]


## 7. Dimensions, Axis, and Shape

How the `axis` parameter controls which dimension an operation collapses, for both 2D and 3D arrays.

**Key concept:** `axis` names the dimension that gets *collapsed* (removed) by the operation — not the direction the result is laid out in.
- **2D array** `(rows, columns)`: `axis=0` collapses the rows → one result per column. `axis=1` collapses the columns → one result per row.
- **3D array** `(pages, rows, columns)`: `axis=0` collapses the pages (combines across pages). `axis=1` collapses the rows (down each page). `axis=2` collapses the columns (across each row).

In [25]:
# dimenions, axis, shape and 2d arrays:

# understanding dimensions:
matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(f"matrix: \n{matrix}")

#axis = 0: collapse rows (operate down columns) -> one value per column
sum_axis0 = np.sum(matrix, axis = 0)
print(f"sum_axis0: \n{sum_axis0}")
print(f"shape of sum_axis0: {sum_axis0.shape}")

#axis=1: collapse columns
print(f"sum_axis1: {np.sum(matrix, axis=1)} and shape is {np.sum(matrix, axis = 1).shape}")


matrix: 
[[1 2 3]
 [4 5 6]
 [7 8 9]]
sum_axis0: 
[12 15 18]
shape of sum_axis0: (3,)
sum_axis1: [ 6 15 24] and shape is (3,)


In [26]:
# three dimenion array:

matrix_3 = np.array([
    [[1,2,3],         # first 2D slice (page 0)
     [4,5,6]],
     [[7,8,9],        # second 2D slice (page 1)
     [10,11,12]]
])

print(f"3D array: \n{matrix_3}")
print(f"shape of 3d array: {matrix_3.shape}")

sum_axis0_3d = np.sum(matrix_3, axis = 0) # here zero refers to pages and will add two pages into one 
print(f"sum_axis0_3d is: \n {sum_axis0_3d}\n and shape is {sum_axis0_3d.shape}") 
sum_axis1_3d = np.sum(matrix_3, axis = 1) # columns added
print(f"sum with axis= 1 is: \n {sum_axis1_3d} \nand shape is {sum_axis1_3d.shape}")

sum_axis2_3d = np.sum(matrix_3, axis = 2) # rows added
print(f"sum with axis= 2 is: \n {sum_axis2_3d} \nand shape is {sum_axis2_3d.shape}")



3D array: 
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
shape of 3d array: (2, 2, 3)
sum_axis0_3d is: 
 [[ 8 10 12]
 [14 16 18]]
 and shape is (2, 3)
sum with axis= 1 is: 
 [[ 5  7  9]
 [17 19 21]] 
and shape is (2, 3)
sum with axis= 2 is: 
 [[ 6 15]
 [24 33]] 
and shape is (2, 2)


## 8. Statistical Operations

Sum, mean, median, standard deviation, variance, min/max, and their index-based versions (argmin/argmax).

In [27]:
# statistics:

arr = np.array([1,2,3,4,5,6,7,8,9,10])
print(f"original array: {arr}")

print(f"Sum: {np.sum(arr)}")
print(f"mean: {np.mean(arr)}")
print(f"median: {np.median(arr)}")
print(f"std dev: {np.std(arr)}")
print(f"variance: {np.var(arr)}")
print(f"min: {np.min(arr)}")
print(f"max: {np.max(arr)}")
print(f"index of min: {np.argmin(arr)}")
print(f"index of max: {np.argmax(arr)}")

print(f"\n\n---NOW 2D ARRAYS---\n")

matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(f"matrix:\n{matrix}")
print(f"sum of all elements: {np.sum(matrix)}")
print(f"column sums: {np.sum(matrix, axis = 0)}")
print(f"row sums: {np.sum(matrix, axis = 1)}")
print(f"mean of each column: {np.mean(matrix, axis = 0)}")
print(f"mean of each row: {np.mean(matrix, axis=1)}")




original array: [ 1  2  3  4  5  6  7  8  9 10]
Sum: 55
mean: 5.5
median: 5.5
std dev: 2.8722813232690143
variance: 8.25
min: 1
max: 10
index of min: 0
index of max: 9


---NOW 2D ARRAYS---

matrix:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
sum of all elements: 45
column sums: [12 15 18]
row sums: [ 6 15 24]
mean of each column: [4. 5. 6.]
mean of each row: [2. 5. 8.]


## 9. Linear Algebra

Element-wise multiplication vs. matrix multiplication, dot product, determinant, inverse, transpose, eigenvalues and eigenvectors.

In [28]:
# linear algebra - matrix multiplication:
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])

print(f"marix a: \n{a}\nand matrix b: \n{b}")

# element wise multiplication (NOT matrix multiplication): 
print(f"element wise multiplication: \n{a*b}")

# dot product of vectors:

v1 = np.array([1,2,3])
v2 = np.array([4,5,6])
print(f"dot product of vectors {v1} and {v2} is {np.dot(v1,v2)}")

# matrix products:
print(f"determinant of a: {np.linalg.det(a)}")
print(f"inverse of a: \n{np.linalg.inv(a)}")
print(f"transpose of a: {a.T}")

# eigen values and eigenvectors:

eigenvals, eigenvecs = np.linalg.eig(a)
print(f"\neigenValues: {eigenvals}")
print(f"EigenVectors: \n{eigenvecs}")


marix a: 
[[1 2]
 [3 4]]
and matrix b: 
[[5 6]
 [7 8]]
element wise multiplication: 
[[ 5 12]
 [21 32]]
dot product of vectors [1 2 3] and [4 5 6] is 32
determinant of a: -2.0000000000000004
inverse of a: 
[[-2.   1. ]
 [ 1.5 -0.5]]
transpose of a: [[1 3]
 [2 4]]

eigenValues: [-0.37228132+0.j  5.37228132+0.j]
EigenVectors: 
[[-0.82456484+0.j -0.41597356+0.j]
 [ 0.56576746+0.j -0.90937671+0.j]]


## 10. Useful Array Methods

Sorting, finding unique elements, and searching with `np.where`.

In [29]:
# useful array methods:

arr = np.array([2,155,3,6,55,87,65,34,6,7,23,4,2,5,6,4,6])
print(f"original array: {arr}")
print(f"Sorted arrays: {np.sort(arr)}") # returns sorted copy
print(f"original array unchanged: {arr}") 
print(f"permanently changed when: {arr.sort()}")
print(f"now array is sorted permanently: {arr}")

# unique elements:
arr_duplicates = np.array([2,2,3,3,4,4,5,5,6,6,7,7,8,8,9])
print(f"duplicated: {arr_duplicates}")
print(f"unique: {np.unique(arr_duplicates)}")
print(f"search where 5 is: {arr[np.where(arr<5)]}")



original array: [  2 155   3   6  55  87  65  34   6   7  23   4   2   5   6   4   6]
Sorted arrays: [  2   2   3   4   4   5   6   6   6   6   7  23  34  55  65  87 155]
original array unchanged: [  2 155   3   6  55  87  65  34   6   7  23   4   2   5   6   4   6]
permanently changed when: None
now array is sorted permanently: [  2   2   3   4   4   5   6   6   6   6   7  23  34  55  65  87 155]
duplicated: [2 2 3 3 4 4 5 5 6 6 7 7 8 8 9]
unique: [2 3 4 5 6 7 8 9]
search where 5 is: [2 2 3 4 4]


## 11. Practical Examples

Space for applying NumPy concepts to worked examples.

In [30]:
# practical examples:

# Simulate a grayscale image (2D array) with values 0-255
# Let's create a simple 10x10 "image"
image = np.random.randint(0, 256, size=(10, 10))
print("Original 'image' (10x10 array):")
print(image)

# Image operations
print(f"\n--- Image Statistics ---")
print(f"Brightness (mean): {np.mean(image):.2f}")
print(f"Contrast (std): {np.std(image):.2f}")
print(f"Min pixel value: {np.min(image)}")
print(f"Max pixel value: {np.max(image)}")

# Brightness adjustment (add constant)
brighter = np.clip(image + 50, 0, 255)  # Clip to valid range
print(f"\nBrightness increased (mean: {np.mean(brighter):.2f})")

# Contrast adjustment (multiply)
contrast = np.clip(image * 1.5, 0, 255)
print(f"Contrast increased (std: {np.std(contrast):.2f})")



Original 'image' (10x10 array):
[[156 132 218 241  20 109 121  30 119  15]
 [211 251 122  39 184 142  31 140 166 221]
 [245 237 153 177  96 111  64 136 186 227]
 [152 236  73 152  42  66  81  49  70  19]
 [165 248  79 140 138 250  95   6 253 203]
 [137 221 100 185  41 179 209 173 114 208]
 [ 17 175 198  13 170 196 191 110 246  13]
 [210 183  89 139   8 215   2  49 159  21]
 [171  26 185  85  87  19  48  76  68 174]
 [141  42   3  34  82 150 244 212 130 142]]

--- Image Statistics ---
Brightness (mean): 129.07
Contrast (std): 74.51
Min pixel value: 2
Max pixel value: 253

Brightness increased (mean: 174.04)
Contrast increased (std: 87.18)


In [31]:
# Simulate student test scores (3 tests, 5 students)
scores = np.array([
    [85, 90, 88],  # Student 1
    [92, 87, 91],  # Student 2
    [78, 82, 80],  # Student 3
    [95, 98, 96],  # Student 4
    [88, 85, 90]   # Student 5
])

print("Test Scores Matrix (5 students, 3 tests):")
print(scores)

# Calculate statistics
print("\n--- Student Statistics ---")
student_averages = np.mean(scores, axis=1)
print("Average score per student:", student_averages)
print("Best student average:", np.max(student_averages))
print("Student with best average (index):", np.argmax(student_averages))

print("\n--- Test Statistics ---")
test_averages = np.mean(scores, axis=0)
print("Average score per test:", test_averages)
print("Hardest test (lowest average):", np.argmin(test_averages))
print("Easiest test (highest average):", np.argmax(test_averages))

# Find students who scored above 90 in all tests
excellent_students = np.all(scores > 90, axis=1)
print("\n--- Excellent Students (all tests > 90) ---")
print("Boolean mask:", excellent_students)
print("Indices:", np.where(excellent_students)[0])
print("Scores of excellent students:")
print(scores[excellent_students])

Test Scores Matrix (5 students, 3 tests):
[[85 90 88]
 [92 87 91]
 [78 82 80]
 [95 98 96]
 [88 85 90]]

--- Student Statistics ---
Average score per student: [87.66666667 90.         80.         96.33333333 87.66666667]
Best student average: 96.33333333333333
Student with best average (index): 3

--- Test Statistics ---
Average score per test: [87.6 88.4 89. ]
Hardest test (lowest average): 0
Easiest test (highest average): 2

--- Excellent Students (all tests > 90) ---
Boolean mask: [False False False  True False]
Indices: [3]
Scores of excellent students:
[[95 98 96]]


## 12. Some key numpy commands

In [32]:
# cheat sheet:

# Array Creation
# np.array(), np.arange(), np.linspace(), np.zeros(), np.ones()
# np.full(), np.eye(), np.random.rand(), np.random.randint()

# Array Information
# .shape, .size, .ndim, .dtype, .itemsize, .nbytes

# Array Manipulation
# .reshape(), .flatten(), .T (transpose)
# np.concatenate(), np.vstack(), np.hstack()
# np.split(), np.array_split()

# Mathematical Operations
# +, -, *, /, **, %, np.sqrt(), np.sin(), np.cos(), np.exp(), np.log()

# Statistical Functions
# np.sum(), np.mean(), np.median(), np.std(), np.var()
# np.min(), np.max(), np.argmin(), np.argmax()
# np.percentile(), np.quantile()

# Linear Algebra
# np.dot(), @ (matrix multiplication)
# np.linalg.det(), np.linalg.inv(), np.linalg.eig()
# np.linalg.solve() (solve linear equations)

# Searching and Sorting
# np.where(), np.argwhere()
# np.sort(), .sort() (in-place)
# np.unique(), np.searchsorted()

# Array Comparison
# ==, !=, <, >, <=, >=
# np.all(), np.any(), np.isnan(), np.isinf()