In [2]:
import numpy as np

In [ ]:
numpy_array = np.array([1,2,3,4,5]) # all elements need to have same type in numpy array

In [4]:
numpy_array+10

array([11, 12, 13, 14, 15])

In [ ]:
arr2 = np.arange(0,10,2) # start, stop, step [start, stop)
print(arr2)

[0 2 4 6 8]


In [22]:
arr3 = np.linspace(0, 200, 5) # start, stop, number of elements
print(arr3)

[  0.  50. 100. 150. 200.]


In [9]:
arr4 = np.zeros(5) # 1 dimensional array of zeroes
print(arr4)

[0. 0. 0. 0. 0.]


In [11]:
arr5 = np.ones(5) # 1 dimensional array of ones
print(arr5)

[1. 1. 1. 1. 1.]


In [12]:
arr6 = np.full(5, 7) # five elements of 7
print(arr6)

[7 7 7 7 7]


In [13]:
identity = np.eye(3)
print(identity)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [15]:
random_arr = np.random.rand(5) # uniform distribution [0, 1)
print(random_arr)

[0.83667746 0.05301329 0.05740774 0.66630243 0.35361463]


In [27]:
random_int = np.random.randint(1, 10, size = 5) # [low, high), size
print(random_int)

[5 5 5 5 7]


In [32]:
arr_int = np.array([1,2,3])
print(arr_int.dtype)


int64


In [34]:
arr_new_type = arr_int.astype(np.float64)
print(arr_new_type.dtype)

float64


In [ ]:
# multidimensional arrays
matrix_2d = np.array([[1,2,3], [4,5,6], [7,8,9]])
print(matrix_2d)
print(matrix_2d.shape) # rows and columns
print(matrix_2d.ndim) # number of dimensions
print(matrix_2d.dtype)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)
2
int64


In [42]:
matrix_3d = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(matrix_3d)
print(matrix_3d.shape)
print(matrix_3d.ndim)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
(2, 2, 3)
3


In [45]:
zeros_2d = np.zeros((3,4))
print(zeros_2d)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [47]:
zeros_3d = np.zeros((3,3))
print(zeros_3d)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [56]:
matrix_3d = np.array([[[1,2,3],[4,5,6]]])
print(matrix_3d)

print(matrix_3d.ndim)
print(matrix_3d.shape)

tarr = matrix_3d.T
print(tarr)

[[[1 2 3]
  [4 5 6]]]
3
(1, 2, 3)
[[[1]
  [4]]

 [[2]
  [5]]

 [[3]
  [6]]]


In [57]:
print(matrix_3d.shape)
print(tarr.shape)

(1, 2, 3)
(3, 2, 1)


In [59]:
# Indexing and Slicing:
# 1D

arr = np.array([3,41,5,68,8,9,5])
print("original array", arr)
print(f"First element {arr[0]}")
print(f"Last element {arr[-1]}")
print(f"elements 1 to 3: {arr[1:4]}")
print(f"every other element: {arr[::2]}")

original array [ 3 41  5 68  8  9  5]
First element 3
Last element 5
elements 1 to 3: [41  5 68]
every other element: [3 5 8 5]


In [67]:
#2D
arr_2d = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(f"original array: \n{arr_2d}")
print(f"element at row 1 and column 2: {arr_2d[1,2]}")
print(f"first row: {arr_2d[0,:]}")
print(f"second column: {arr_2d[:,2]}")
print(f"submatrix: first 2 rows and first 2 columns: {arr_2d[ 0:2, 0:2]}")


original array: 
[[1 2 3]
 [4 5 6]
 [7 8 9]]
element at row 1 and column 2: 6
first row: [1 2 3]
second column: [3 6 9]
submatrix: first 2 rows and first 2 columns: [[1 2]
 [4 5]]


In [70]:
# boolean indexing
nums = np.array([1,4,2,5,6,7,3,2,6,7,9,7,5,55,33,43,55,67,87,87])
print(f"elements greater than 10: {nums[nums > 10]}")
print(f"elements that are even: {nums[nums%2==0]}")

elements greater than 10: [55 33 43 55 67 87 87]
elements that are even: [4 2 6 2 6]
